// Firebase initialization for MeetRandom - autogenerated
// NOTE: keep this file secret in production or use environment variables.
const firebaseConfig = {
  "apiKey": "AIzaSyDoKxf1_txjT13skCt7HcsYiZbuff1z8rs",
  "authDomain": "meetrandom-f05cb.firebaseapp.com",
  "projectId": "meetrandom-f05cb",
  "storageBucket": "meetrandom-f05cb.firebasestorage.app",
  "messagingSenderId": "501832650154",
  "appId": "1:501832650154:web:ee5d01514b56c5e3ae2fd3",
  "measurementId": "G-GJ9Q7G88S5",
  "databaseURL": "https://meetrandom-f05cb-default-rtdb.europe-west1.firebasedatabase.app"
};

// Load Firebase SDKs (v9 modular via CDN - works on static hosting)
(function(){ 
  const head = document.getElementsByTagName('head')[0];
  const scripts = [
    'https://www.gstatic.com/firebasejs/9.22.2/firebase-app-compat.js',
    'https://www.gstatic.com/firebasejs/9.22.2/firebase-auth-compat.js',
    'https://www.gstatic.com/firebasejs/9.22.2/firebase-database-compat.js',
    'https://www.gstatic.com/firebasejs/9.22.2/firebase-firestore-compat.js'
  ];
  scripts.forEach(src => { const s = document.createElement('script'); s.src = src; head.appendChild(s); });
})();
function initFirebaseOnLoad() {
  if (!window.firebase) return setTimeout(initFirebaseOnLoad, 50);
  firebase.initializeApp(firebaseConfig);
  // Expose helpers
  window.auth = firebase.auth();
  window.db = firebase.firestore();
  window.rtdb = firebase.database();
}
document.addEventListener('DOMContentLoaded', initFirebaseOnLoad);
